# Generated by Django 5.2 on 2025-05-14 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Followstreamboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        db_column="board_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pinboard",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        db_column="stream_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_links",
                        to="core.followstream",
                    ),
                ),
            ],
            options={
                "db_table": "followstreamboard",
                "unique_together": {("stream", "board")},
            },
        ),
    ]
