# Generated by Django 5.2 on 2025-05-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_followstreamboard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pinboard",
            options={"managed": True},
        ),
    ]
