from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_redirect, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('pinboards/', views.pinboard_list, name='pinboard_list'),
    path('pinboards/create/', views.pinboard_create, name='pinboard_create'),
    path('pinboards/<int:board_id>/pin/', views.pin_image, name='pin_image'),
    path('feed/', views.pin_feed, name='pin_feed'),
    path('repin/<int:pin_id>/', views.repin_select_board, name='repin_select_board'),
    path('pinboards/<int:board_id>/', views.board_detail, name='board_detail'),
    path('image/<int:image_id>/', views.image_blob_view, name='image_blob'),
    path('like/', views.like_pin, name='like_pin'),
    path('comment/', views.comment_pin, name='comment_pin'),
    path('friends/request/', views.send_friend_request, name='send_friend_request'),
    path('friends/requests/', views.friend_requests_view, name='friend_requests'),
    path('friends/handle/<int:requester_id>/<str:action>/', views.handle_friend_request, name='handle_friend_request'),
    path('friends/', views.friend_list, name='friend_list'),
    path('profile/<int:user_id>/', views.profile_view, name='profile'),
    path('streams/', views.follow_streams_view, name='follow_streams'),
    path('streams/create/', views.create_follow_stream, name='create_follow_stream'),
    path('boards/browse/', views.browse_boards, name='browse_boards'),
    path('boards/<int:board_id>/add/', views.add_board_to_stream, name='add_board_to_stream'),
    path('streams/<int:stream_id>/', views.follow_stream_detail, name='follow_stream_detail'),
    path('search/', views.search_pins, name='search_pins'),
    path('boards/<int:board_id>/add_to_stream/', views.add_to_follow_stream, name='add_to_stream'),
    path('profile/<int:user_id>/friends/', views.profile_friends_view, name='profile_friends'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('pin/<int:pin_id>/', views.pin_detail, name='pin_detail'),
    path('pin/delete/<int:pin_id>/', views.delete_pin, name='delete_pin'),
    path('friends/unfriend/', views.unfriend, name='unfriend'),
    path('dashboard/stream/<int:stream_id>/', views.dashboard, name='dashboard_stream'),
    # “Select a board” entrypoint
    path('pin/new/', views.pin_image, name='create_pin'),
    # “Pin to this board” entrypoint
    path('pin/new/<int:board_id>/', views.pin_image, name='pin_image'),
    path('pin/create/', views.pin_image, name='create_pin'),
    path('pin/create/<int:board_id>/', views.pin_image, name='pin_image'),
    path('boards/<int:board_id>/add_to_stream/', views.add_to_follow_stream, name='add_to_follow_stream'),
    path('pinboard/delete/<int:board_id>/', views.delete_pinboard, name='delete_pinboard'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('follow_streams/delete/<int:stream_id>/', views.delete_follow_stream, name='delete_follow_stream'),
    path('dashboard/<int:stream_id>/', views.dashboard, name='dashboard'),
]

